services:

  server:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      memgraph:
        condition: service_started
      # memgraph:
        # condition: service_healthy
    env_file:
      - "./config/.env"
    # environment:
    #   - CONFIG_PATH="./config/deploy.yaml"

  postgres:
    image: "postgres:13.22-alpine3.22"
    ports:
      - "5433:5432"
    env_file:
      - "./postgres.env"
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  
  memgraph:
    image: "memgraph/memgraph:latest"
    # volumes:
    #   - ./data/memgraph/lib:/var/lib/memgraph
    #   - ./data/memgraph/log:/var/log/memgraph
    #   - ./memgraph-import:/import
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:7687 || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 20s
