server:
  address: 0.0.0.0:8080

bot:
  username: "t21_hakaton_bot"

mini-app:
  proto: http
  host: localhost
  port: 8080

postgres:
  host: postgres
  port: 5432
  database: postgres
  ssl_mode: disable

memgraph:
  protocol: bolt
  host: memgraph
  port: 7687

jwt:
  token_ttl_seconds: 86400